# Generated by Django 4.2.3 on 2023-07-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_customer_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(choices=[('4', '4 months'), ('6', '6 months')], max_length=1, null=True)),
            ],
        ),
    ]
